# -*- coding: utf-8 -*-
"""Runtime wrapper for convert_thread extracted from office_converter.py."""


def convert_logic_in_thread_for_converter(
    converter,
    file_source,
    sandbox_target_pdf,
    ext,
    result_context,
    *,
    convert_logic_in_thread_fn,
    is_mac_fn,
    has_win32,
    engine_wps,
    wd_format_pdf,
    xl_type_pdf,
    pp_save_as_pdf,
    pp_fixed_format_type_pdf,
    xl_pdf_save_as,
    xl_repair_file,
    strategy_standard,
    strategy_price_only,
    pythoncom_module,
    os_module,
):
    return convert_logic_in_thread_fn(
        file_source,
        sandbox_target_pdf,
        ext,
        result_context,
        is_mac_fn=is_mac_fn,
        convert_on_mac_fn=converter._convert_on_mac,
        has_win32=has_win32,
        allowed_extensions=converter.config.get("allowed_extensions", {}),
        get_local_app_fn=converter._get_local_app,
        safe_exec_fn=converter._safe_exec,
        engine_type=converter.engine_type,
        engine_wps=engine_wps,
        wdFormatPDF=wd_format_pdf,
        xlTypePDF=xl_type_pdf,
        ppSaveAsPDF=pp_save_as_pdf,
        ppFixedFormatTypePDF=pp_fixed_format_type_pdf,
        xlPDF_SaveAs=xl_pdf_save_as,
        xlRepairFile=xl_repair_file,
        content_strategy=converter.content_strategy,
        strategy_standard=strategy_standard,
        strategy_price_only=strategy_price_only,
        scan_excel_content_in_thread_fn=converter.scan_excel_content_in_thread,
        setup_excel_pages_fn=converter._setup_excel_pages,
        should_reuse_office_app_fn=converter._should_reuse_office_app,
        pythoncom_module=pythoncom_module,
        os_module=os_module,
    )
