# -*- coding: utf-8 -*-
"""Default config helpers extracted from office_converter.py."""

import json

from converter.constants import (
    COLLECT_MODE_COPY_AND_INDEX,
    MERGE_CONVERT_SUBMODE_MERGE_ONLY,
    MERGE_MODE_CATEGORY,
    MODE_CONVERT_THEN_MERGE,
    STRATEGY_STANDARD,
)


def create_default_config(config_path):
    """Create a default config file."""
    try:
        default_config = {
            "source_folder": "C:\\Docs",
            "source_folders": ["C:\\Docs"],
            "target_folder": "C:\\PDFs",
            "source_folder_win": "C:\\Docs",
            "source_folders_win": ["C:\\Docs"],
            "target_folder_win": "C:\\PDFs",
            "source_folder_mac": "",
            "source_folders_mac": [],
            "target_folder_mac": "",
            "app_mode": "classic",
            "log_folder": "./logs",
            "enable_sandbox": True,
            "default_engine": "ask",
            "kill_process_mode": "ask",
            "auto_retry_failed": False,
            "enable_failed_file_trace_log": True,
            "office_reuse_app": True,
            "office_restart_every_n_files": 25,
            "timeout_seconds": 60,
            "pdf_wait_seconds": 15,
            "ppt_timeout_seconds": 180,
            "ppt_pdf_wait_seconds": 30,
            "enable_merge": True,
            "output_enable_pdf": True,
            "output_enable_md": True,
            "output_enable_merged": True,
            "output_enable_independent": False,
            "merge_convert_submode": MERGE_CONVERT_SUBMODE_MERGE_ONLY,
            "enable_corpus_manifest": True,
            "markdown_strip_header_footer": True,
            "markdown_structured_headings": True,
            "enable_markdown_quality_report": True,
            "markdown_quality_sample_limit": 20,
            "enable_excel_json": False,
            "enable_chromadb_export": False,
            "chromadb_persist_dir": "",
            "chromadb_collection_name": "office_corpus",
            "chromadb_max_chars_per_chunk": 1800,
            "chromadb_chunk_overlap": 200,
            "chromadb_write_jsonl_fallback": True,
            "enable_incremental_mode": False,
            "incremental_verify_hash": False,
            "incremental_reprocess_renamed": False,
            "incremental_registry_path": "",
            "enable_parallel_conversion": False,
            "parallel_workers": 4,
            "enable_checkpoint": True,
            "checkpoint_auto_resume": True,
            "source_priority_skip_same_name_pdf": False,
            "global_md5_dedup": False,
            "enable_update_package": True,
            "update_package_root": "",
            "cab_7z_path": "",
            "mshelpviewer_folder_name": "MSHelpViewer",
            "enable_mshelp_merge_output": True,
            "enable_mshelp_output_docx": False,
            "enable_mshelp_output_pdf": False,
            "excel_json_max_rows": 2000,
            "excel_json_max_cols": 80,
            "excel_json_records_preview": 200,
            "excel_json_profile_rows": 500,
            "excel_json_include_formulas": True,
            "excel_json_extract_sheet_links": True,
            "excel_json_include_merged_ranges": True,
            "excel_json_formula_sample_limit": 200,
            "excel_json_merged_range_limit": 500,
            "max_merge_size_mb": 80,
            "merge_filename_pattern": "Merged_{category}_{timestamp}_{idx}",
            "price_keywords": ["报价", "价格表", "Price", "Quotation"],
            "excluded_folders": ["temp", "backup", "archive"],
            "allowed_extensions": {
                "word": [".doc", ".docx"],
                "excel": [".xls", ".xlsx"],
                "powerpoint": [".ppt", ".pptx"],
                "pdf": [".pdf"],
                "cab": [".cab"],
            },
            "overwrite_same_size": True,
            "merge_mode": MERGE_MODE_CATEGORY,
            "run_mode": MODE_CONVERT_THEN_MERGE,
            "collect_mode": COLLECT_MODE_COPY_AND_INDEX,
            "content_strategy": STRATEGY_STANDARD,
            "merge_source": "target",
            "temp_sandbox_root": "",
            "temp_sandbox_root_win": "",
            "temp_sandbox_root_mac": "",
            "sandbox_min_free_gb": 10,
            "sandbox_low_space_policy": "block",
            "enable_llm_delivery_hub": True,
            "llm_delivery_root": "",
            "llm_delivery_root_win": "",
            "llm_delivery_root_mac": "",
            "obsidian_sync_enabled": True,
            "obsidian_root": "",
            "obsidian_program_name": "ZhiWei",
            "llm_delivery_flatten": True,
            "llm_delivery_include_pdf": False,
            "enable_gdrive_upload": False,
            "gdrive_client_secrets_path": "",
            "gdrive_folder_id": "",
            "gdrive_token_path": "",
            "enable_upload_readme": True,
            "enable_upload_json_manifest": True,
            "upload_dedup_merged": True,
            "enable_merge_index": False,
            "enable_merge_excel": False,
            "enable_merge_map": True,
            "bookmark_with_short_id": True,
            "everything": {
                "enabled": True,
                "es_path": "",
                "prefer_path_exact": True,
                "timeout_ms": 1500,
            },
            "listary": {"enabled": True, "copy_query_on_locate": True},
            "privacy": {"mask_md5_in_logs": True},
            "ui": {
                "tooltip_delay_ms": 500,
                "tooltip_bg": "#FFF7D6",
                "tooltip_fg": "#202124",
                "tooltip_font_family": "System",
                "tooltip_font_size": 9,
                "tooltip_auto_theme": True,
                "confirm_revert_dirty": True,
                "task_current_config_only": True,
            },
        }
        with open(config_path, "w", encoding="utf-8") as f:
            json.dump(default_config, f, indent=4, ensure_ascii=False)
        print(f"Default config created: {config_path}")
        return True
    except Exception as e:
        print(f"Failed to create default config: {e}")
        return False
